Analyse-conception
cnmh/conception-generique pull request #18
Opened 2024-01-15 13:43 UTC by husseinbouik

- Realisation d'analyse-conception
  - Analyse technique
  - Diagramme de cas d'utilisation
  - Diagramme de classe

2024-01-15 13:53 UTC, imranesarsri requested changes

2024-01-15 13:53 UTC, imranesarsri commented on Analyse-conception/Analyse-conception.md
> +## Travail à faire
supprimer travail a faire

2024-01-15 13:53 UTC, imranesarsri commented on backlog-conception-generique/Analyse-conception.md
> +- Diagramme de classe
## Liste des livrables 
 - Fichier Markdown (Empathie.md)
   - github/cnmh/besoin/Empathie 
 - Google slide :
   - [Réalisation-besoin](https://docs.google.com/presentation/d/1WkibTkxVvAtEwSUtbnktpjZTRztYOJby6Cckc1bsjlg/edit#slide=id.g2acef800187_3_44)

2024-01-15 14:49 UTC, essarraj-fouad commented
Essayer de mettre le travail en markdown

2024-01-16 14:03 UTC, imranesarsri approved these changes

2024-01-17 11:13 UTC, essarraj-fouad approved these changes
Non valide

2024-01-17 12:08 UTC, merged